### PR TITLE
Add "newexposure" to ZWO configuration file

### PR DESCRIPTION
**Pull request by EricClaeys**

### CODE REVIEW

**Review by thomasjacquin — APPROVED** [review]

**Comment by EricClaeys** [comment]
Thomas,

The allsky-portal dev branch is 6 commits ahead and 2 behind the master.


Eric

**Comment by thomasjacquin** [comment]
hmm... usually, the branch merged into master gets deleted. I just leave it around so people can commit to it.

You could merge `origin/master` into the dev branch and I think that would fix it.

```
git fetch
git checkout dev
git merge origin/master
git push
```

That should update the dev branch and bring it up to date with `master`.

**Comment by EricClaeys** [comment]
Thomas,

 

Since you created the dev branch I haven’t been using my own fork – I just commit to the allsky, allsky-portal, and allsky-website dev branches.  They are the ones that are out of sync with the corresponding master branches.

I’ve never had any luck using the “git” command on my PC since it doesn’t seem to update the website’s GitHub.

 

Eric

**Comment by thomasjacquin** [comment]
@EricClaeys I delete the `origin/dev` branch. I believe it will create a new one the next time you push your changes. It it doesn't work, let me know and I'll manually re-create a new one.

**Pull request merged**
