### PR TITLE
Enable "LAN Connection Status" link.

### PR DESCRIPTION
**Pull request by EricClaeys**
This allows users to see the status and information on the LAN connection, and start/stop it.  It's similar to the WLAN data.

### CODE REVIEW

**Comment by thomasjacquin** [comment]
@EricClaeys Is this PR not relevant anymore? If the concern is the inclusion of all the commits, I can just squash all of them into 1 commit and merge into `master`. What matters to me is the last tab "Files Changed".

**Comment by EricClaeys** [comment]
Thomas,

It’s still relevant.

I’ve run all the “git” commands on my Pi, in ~/allsky, /var/www/html, and /var/www/html/allsky for the three packages, and it has no impact on the GitHub web pages – they still say my branch is X commits ahead of yours, and in some cases also a few behind yours.  So whenever I do  PR it wants to include all of my commits.

If you can squash the ones already done, then I won’t worry about the differences, but do you know how I can get my branch on the GitHub web page to be in sync with yours?

 

Eric

**Comment by thomasjacquin** [comment]
You could try to rebase your branch on top of master. First fetch the latest code. Then from your branch `git rebase origin/master` should bring you on top of master.

**Comment by EricClaeys** [comment]
Thomas,

I have been using the GitHub we pages to make all changes and do the PRs.  And it is what is "ahead" and "behind" your master.  When I ran the "git" commands you suggested on the Pi, it made no difference on the web.

Is there a way to rebase my web fork?

Eric
________________________________

**Comment by thomasjacquin** [comment]
Don't worry about this PR, I've merged it already. Just try making a new branch every time you make a new feature. As the feature gets merged, the branch is then deleted.

**Pull request merged**
