### PR TITLE
camera_settings.php: $display bug fix

### PR DESCRIPTION
**Pull request by EricClaeys**

### CODE REVIEW

**Comment by thomasjacquin** [comment]
@EricClaeys The fix looks good.

While you're modifying that file, can you remove any hardcoded color you've recently added to the text inputs and borders?
It is impacting the dark theme negatively.
I try to keep styling away from content by placing it in CSS files. That way, when the dark theme is used, it's picking up the  right CSS.

image

**Comment by EricClaeys** [comment]
@thomasjacquin I can create a dark theme in the .css file for the input background color and the line border.  I was finding it hard to know where one description ended and another started, and the line border solved that.  The input color was just to make it look nicer.
I will also remove the style from the .php file.

Should I make those changes using this PR, or a new one?  This PR fixes what can be a major bug.

**Comment by thomasjacquin** [comment]
@EricClaeys 
Sorry, I didn't see your reply earlier. There is already a CSS file that handles the themes. It's in `dist/css/custom.css`.
The way it works is the following: When you select the dark theme, it adds the `.dark` class at the top of the DOM so it's easy to override elements in CSS afterwards.
You can just fix those 2 (input background and horizontal bar) in this PR and we'll look at other improvements later.

**Comment by EricClaeys** [comment]
@thomasjacquin   I created ".dark" entries for the items I added, as well as for the buttons and alert messages.  In Dark mode everything is now dark.
Let me know what you think.

**Review by thomasjacquin — APPROVED** [review]
Yes, Looks good to me now.

**Pull request merged**
